### ISSUE TITLE
Local GMT time?

### ISSUE THREAD

**Issue by ferazambuja** [jonathanmeaney/unicorn-hat-hd-clock#1]
Cool project. I've been using on my desk.
Is there a simple way to get my local time? GMT?

**Comment by jonathanmeaney** [comment]
Hey, it should use whatever time your system is set to. If you are using Raspian you can update the localisation options on your Raspberry Pi by running `sudo raspi-config` on the terminal and then picking **Localisation Options** and then pick **Change Time Zone** and select the appropriate time zone for you. I had to do this too as my Raspian setup was showing the incorrect time. Hope that helps!

**Comment by ferazambuja** [comment]
I forgot that I haven't change it in my testing RPi.
